---
title: "csv-generator/graph-maker"
author: "Emiliano Sánchez Escalante"
date: "17/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, libraries}
library(ggplot2)
library(tidyr)
library(cluster)
library(SimilarityMeasures)
library(kmlShape)
```

```{r, Chunk1}
set.seed(160396)
setwd("C:/Users/Lenovo/Documents/CoRa/InputFiles/")
generate <- function(rows){
  g <- sample(seq(from = 0.0001, to = 1, by = 0.00001), rows)
  mY <- rep(0.125, rows)
  gY <- sample(seq(from = 0.01, to = 100, by = 0.001), rows)
  mU <- sample(seq(from = 0.00125, to = 12.5, by = 0.000125), rows)
  gU <- sample(seq(from = 0.000001, to = 0.01, by = 0.0000001), rows)
  mW <- sample(seq(from = 0.001, to = 10, by = 0.0001), rows)
  gW <- sample(seq(from = 0.000001, to = 0.01, by = 0.0000005), rows)
  e0 <- sample(seq(from = 0.000001, to = 0.01, by = 0.0000005), rows)
  eP <- sample(seq(from = 0.000375, to = 3.75, by = 0.0000375), rows)
  eM <- sample(seq(from = 0.005, to = 50, by = 0.0005), rows)
  mUs <- rep(NaN, rows)
  
  csv <- data.frame(g, mY, gY, mU, gU, mW, gW, e0, eP, eM, mUs)
  
  return(csv)
}
write.csv(generate(100), file = "ARGS_ATFv2_Mass_Par_Fig2B.csv", row.names = FALSE)
```

```{r, chunk2}
setwd("C:/Users/Lenovo/Documents/CoRa/")
CoRas <- as.data.frame(t(read.table(file = "OUT_ExSSs_ATFv2_Fig2B_mY_mY.txt", header = T)))
CoRas <- CoRas[2:nrow(CoRas),]
CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- paste0("Attempt", 1:ncol(CoRas))
Graphing <- tidyr::gather(CoRas)
# test$value[test$value>1] <- NaN
Graphing$step <- rep(1:nrow(CoRas), ncol(CoRas))
a <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none")
a
```

```{r, chunk3}
FreDistances <- function(frame){
  DissimMatrix <- matrix(0, ncol = ncol(frame), nrow = ncol(frame))
  for(i in 1:ncol(frame)){
    path1dat <- frame[,i][is.finite(frame[,i])]
    path1 <- matrix(c(1:length(path1dat), path1dat), length(path1dat), byrow = F)
    for(j in i:ncol(frame)){
      if(i == j){
        DissimMatrix[i,j] <- 0
      }else{
        path2dat <- frame[,j][is.finite(frame[,j])]
        path2 <- matrix(c(1:length(path2dat), path2dat), length(path2dat), byrow = F)
        
        DissimMatrix[i,j] <- Frechet(path1, path2)
        print(paste0("Fréchet distance between curves ", i, " and ", j, " calculated"))
      }
    }
  }
  DissimMatrix[lower.tri(DissimMatrix)] <- t(DissimMatrix)[lower.tri(DissimMatrix)]
  return(DissimMatrix)
}
```

```{r, chunk4}
#DissimMat <- FreDistances(CoRas[,1:6])
#DissimMat
```

```{r, chunk5}
uwu <- pam(DissimMatManip, diss = T, k = 3)
plot(uwu)
```

```{r, chunk7}
SquDistances <- function(frame){
  DissimMatrix <- matrix(0, ncol = ncol(frame), nrow = ncol(frame))
  colnames(DissimMatrix) <- colnames(frame)
  for(i in 1:ncol(frame)){
    curve1 <- frame[,i]
    curve1[is.nan(curve1)] <- 0
    for(j in i:ncol(frame)){
      if(i == j){
        DissimMatrix[i,j] <- 0
      }else{
        curve2 <- frame[,j]
        curve2[is.nan(curve2)] <- 0
        DissimMatrix[i,j] <- mean((curve1 - curve2)**2)
      }
    }
  }
  DissimMatrix[lower.tri(DissimMatrix)] <- t(DissimMatrix)[lower.tri(DissimMatrix)]
  return(DissimMatrix)
}
```

```{r, chunk8}
DissimMat2 <- SquDistances(CoRas)
DissimMat2
```

```{r, chunk9}
owo <- pam(DissimMat2, diss = T, k = 3)
owo$silinfo$avg.width
plot(owo)
plot(hclust(as.dist(DissimMat2), method = "average"))
```

```{r, chunk10}
test1dat <- matrix(c(1:length(CoRas[,1][is.finite(CoRas[,1])]), CoRas[,1][is.finite(CoRas[,1])]), length(CoRas[,1][is.finite(CoRas[,1])]), byrow = F)
head(test1dat)

as.matrix(DouglasPeuckerEpsilon(test1dat[,1], test1dat[,2], epsilon = 0.01))
```

```{r, chunk11}
DPFreDistances <- function(frame){
  DissimMatrix <- matrix(0, ncol = ncol(frame), nrow = ncol(frame))
  colnames(DissimMatrix) <- colnames(frame)
  for(i in 1:ncol(frame)){
    path1dat <- frame[,i][is.finite(frame[,i])]
    path1 <- matrix(c(1:length(path1dat), path1dat), length(path1dat), byrow = F)
    path1 <- as.matrix(DouglasPeuckerEpsilon(path1[,1], path1[,2], epsilon = 0.01))
    for(j in i:ncol(frame)){
      if(i == j){
        DissimMatrix[i,j] <- 0
      }else{
        path2dat <- frame[,j][is.finite(frame[,j])]
        path2 <- matrix(c(1:length(path2dat), path2dat), length(path2dat), byrow = F)
        path2 <- as.matrix(DouglasPeuckerEpsilon(path2[,1], path2[,2], epsilon = 0.01))
        
        DissimMatrix[i,j] <- Frechet(path1, path2)
        print(paste0("Fréchet distance between simplified curves ", i, " and ", j, " calculated"))
      }
    }
  }
  DissimMatrix[lower.tri(DissimMatrix)] <- t(DissimMatrix)[lower.tri(DissimMatrix)]
  return(DissimMatrix)
}

DPDissimMatrix <- DPFreDistances(CoRas)
head(DPDissimMatrix)
```

```{r, chunk12}
DPuwu <- pam(DPDissimMatrix, diss = T, k = 5)
plot(DPuwu)

plot(hclust(as.dist(DPDissimMatrix), method = "average"))
```

```{r, chunk13}
testline <- matrix(c(1:601, rep(1, 601)), byrow = F, ncol = 2)
head(testline)

#withoutDP <- Frechet(test1dat, testline)

testline <- as.matrix(DouglasPeuckerEpsilon(testline[,1], testline[,2], epsilon = 0.01))

#withDP <- Frechet(test1dat, testline)

Error <- (withoutDP - withDP)
Error
```

```{r, chunk14}
ErrorCheck <- function(frame){
  DissimMatrix <- matrix(0, ncol = ncol(frame), nrow = ncol(frame))
  DissimMatrixUnsimp <- matrix(0, ncol = ncol(frame), nrow = ncol(frame))
  colnames(DissimMatrix) <- colnames(frame)
  for(i in 1:ncol(frame)){
    path1dat <- frame[,i][is.finite(frame[,i])]
    path1 <- matrix(c(1:length(path1dat), path1dat), length(path1dat), byrow = F)
    path1unsimp <- path1
    path1 <- as.matrix(DouglasPeuckerEpsilon(path1[,1], path1[,2], epsilon = 0.01))
    for(j in i:ncol(frame)){
      if(i == j){
        DissimMatrix[i,j] <- 0
      }else{
        path2dat <- frame[,j][is.finite(frame[,j])]
        path2 <- matrix(c(1:length(path2dat), path2dat), length(path2dat), byrow = F)
        path2 <- as.matrix(DouglasPeuckerEpsilon(path2[,1], path2[,2], epsilon = 0.01))
        
        DissimMatrix[i,j] <- Frechet(path1, path2)
        print(paste0("Fréchet distance between curves ", i, " and ", j, " calculated"))
        DissimMatrixUnsimp[i,j] <- Frechet(path1unsimp, path2)
        print(paste0("Fréchet distance between unsimplified curve ", i, " and curve ", j, " calculated"))
      }
    }
  }
  DissimMatrix[lower.tri(DissimMatrix)] <- t(DissimMatrix)[lower.tri(DissimMatrix)]
  DissimMatrixUnsimp[lower.tri(DissimMatrixUnsimp)] <- t(DissimMatrixUnsimp)[lower.tri(DissimMatrixUnsimp)]
  ErrorMat <- (DissimMatrixUnsimp - DissimMatrix) / DissimMatrixUnsimp
  return(ErrorMat)
}
```


```{r, chunk15}
Error <- ErrorCheck(CoRas)
```


```{r, chunk16}
max(Error[is.finite(Error)])
min(Error[is.finite(Error)])
mean(Error[is.finite(Error)])

sd(Error[1,][is.finite(Error[1,])])
#write.csv(Error, file = "Error_Matrix_Seed_160396.csv")
```
```{r, chunk17}
ErrorColMeans <- c()

for (i in 1:ncol(Error)){
  ErrorColMeans[i] <- mean(Error[,i][is.finite(Error[,i])])
}
mean(ErrorColMeans)
```

```{r, chunk18}
mean(abs(Error[which(abs(Error) <= 50)]))
```