---
title: "Finding_Epsilon"
author: "Emiliano Sánchez Escalante"
date: "24/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries}
library(ggplot2)
library(ggpubr)
library(tidyr)
library(tidyverse)
library(cluster)
library(SimilarityMeasures)
library(kmlShape)
library(dendextend)
library(seriation)
library(factoextra)
library(data.table)
```

```{r, Defining_Functions}
ATF_generate <- function(rows, c){
  g <- 1 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mY <- rep(0.125, rows)
  gY <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mU <- 1.25 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  gU <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  mW <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  gW <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  e0 <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  eP <- 3.75 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  eM <- 5 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mUs <- rep(NaN, rows)
  
  csv <- data.frame(g, mY, gY, mU, gU, mW, gW, e0, eP, eM, mUs)
  
  return(csv)
}

BNF_generate <- function(rows, c){
  g <- 1 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mY <- rep(0.125, rows)
  gY <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mU <- 2 * 10** sample(seq(from = (0 - c/2), to = (0 + c/2), by = 0.01), rows, replace = T)
  kD <- 1 * 10** sample(seq(from = (0 - c/2), to = (0 + c/2), by = 0.01), rows, replace = T)
  gU <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  b <- 1.08 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  bs <- 1.565 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mUs <- rep(NaN, rows)
  
  csv <- data.frame(g, mY, gY, mU, kD, gU, b, bs, mUs)
  
  return(csv)
}

BMF2_generate <- function(rows, c){
  g <- 1 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mY <- rep(0.125, rows)
  gY <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mA <- 3.72 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  kD <- 1 * 10** sample(seq(from = (-0 - c/2), to = (-0 + c/2), by = 0.01), rows, replace = T)
  mB <- 1.25 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mU <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  e0 <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  eP <- 5 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  bA <- 5 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  bI <- 5 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mAs <- rep(NaN, rows)
  
  csv <- data.frame(g, mY, gY, mA, kD, mB, mU, e0, eP, bA, bI, mAs)
  
  return(csv)
}

BMF1_generate <- function(rows, c){
  g <- 1 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mY <- rep(0.125, rows)
  gY <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mA <- 3.38 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mB <- 1.25 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mU <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  e0 <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  eP <- 5 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  bA <- 5 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  bI <- 5 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mBs <- rep(NaN, rows)
  
  csv <- data.frame(g, mY, gY, mA, mB, mU, e0, eP, bA, bI, mBs)
  
  return(csv)
}

FAD_generate <- function(rows, c){
  g <- 1 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mY <- rep(0.125, rows)
  gY <- 1 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mU <- 1.25 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  gU <- 5 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  mW <- 3.27 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  gW <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  e0 <- 1 * 10** sample(seq(from = (-4 - c/2), to = (-4 + c/2), by = 0.01), rows, replace = T)
  eP <- 3.75 * 10** sample(seq(from = (-2 - c/2), to = (-2 + c/2), by = 0.01), rows, replace = T)
  eM <- 5 * 10** sample(seq(from = (-1 - c/2), to = (-1 + c/2), by = 0.01), rows, replace = T)
  mUs <- rep(NaN, rows)

  csv <- data.frame(g, mY, gY, mU, gU, mW, gW, e0, eP, eM, mUs)
  
  return(csv)
}

FreDistances <- function(frame){
  DissimMatrix <- matrix(0, ncol = ncol(frame), nrow = ncol(frame))
  for(i in 1:ncol(frame)){
    path1dat <- frame[,i][is.finite(frame[,i])]
    path1 <- matrix(c(1:length(path1dat), path1dat), length(path1dat), byrow = F)
    for(j in i:ncol(frame)){
      if(i == j){
        DissimMatrix[i,j] <- 0
      }else{
        path2dat <- frame[,j][is.finite(frame[,j])]
        path2 <- matrix(c(1:length(path2dat), path2dat), length(path2dat), byrow = F)
        
        DissimMatrix[i,j] <- Frechet(path1, path2)
        print(paste0("Fréchet distance between curves ", i, " and ", j, " calculated"))
      }
    }
  }
  DissimMatrix[lower.tri(DissimMatrix)] <- t(DissimMatrix)[lower.tri(DissimMatrix)]
  return(DissimMatrix)
}

DPFreDistances <- function(frame, Epsi){
  DissimMatrix <- matrix(0, ncol = ncol(frame), nrow = ncol(frame))
  colnames(DissimMatrix) <- colnames(frame)
  for(i in 1:ncol(frame)){
    path1dat <- frame[,i][is.finite(frame[,i])]
    path1 <- matrix(c(1:length(path1dat), path1dat), length(path1dat), byrow = F)
    path1 <- as.matrix(DouglasPeuckerEpsilon(path1[,1], path1[,2], epsilon = Epsi))
    for(j in i:ncol(frame)){
      if(i == j){
        DissimMatrix[i,j] <- 0
      }else{
        path2dat <- frame[,j][is.finite(frame[,j])]
        path2 <- matrix(c(1:length(path2dat), path2dat), length(path2dat), byrow = F)
        path2 <- as.matrix(DouglasPeuckerEpsilon(path2[,1], path2[,2], epsilon = Epsi))
        
        DissimMatrix[i,j] <- Frechet(path1, path2)
        print(paste0("Fréchet distance between simplified curves ", i, " and ", j, " calculated"))
      }
    }
  }
  DissimMatrix[lower.tri(DissimMatrix)] <- t(DissimMatrix)[lower.tri(DissimMatrix)]
  return(DissimMatrix)
}

ErrorMat <- function(frame, control, Epsi){
  Unsimplified <- control
  Simplified <- DPFreDistances(frame, Epsi)
  ErrorMatrix <- abs(((Simplified - Unsimplified) / Unsimplified))
  return(ErrorMatrix)
}

ErrorCheck <- function(ErrorMatrix, Epsi){
  Maximum_Error <- max(ErrorMatrix[is.finite(ErrorMatrix)])
  Average_Error <- mean(ErrorMatrix[is.finite(ErrorMatrix)])
  Minimum_Error <- min(ErrorMatrix[is.finite(ErrorMatrix)])
  SD_of_Error <- sd(ErrorMatrix[is.finite(ErrorMatrix)])
  
  Summary <- data.frame(Maximum_Error, Average_Error, Minimum_Error, SD_of_Error, Epsi)
  
  return(Summary)
}
```

```{r, Creating_infile_ATF}
set.seed(041219)
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/InputFiles/") #Cambiar a carpeta relevante dependiendo de computadora
write.csv(ATF_generate(1250, 6), file = "ARGS_ATFv2_Mass_Par_1250Set2.csv", row.names = FALSE)
```
```{r, Creating_infile_BNF}
set.seed(041219)
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/InputFiles/") #Cambiar a carpeta relevante dependiendo de computadora
write.csv(BNF_generate(1250, 6), file = "ARGS_BNFv1_Mass_Par_1250Set1.csv", row.names = FALSE)
```

```{r, Creating_infile_BMF2}
set.seed(160396)
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/InputFiles/") #Cambiar a carpeta relevante dependiendo de computadora
write.csv(BMF2_generate(1250, 0), file = "ARGS_BMFv2_Mass_Par_1250Set1.csv", row.names = FALSE)
```

```{r, Creating_infile_BMF1}
set.seed(160396)
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/InputFiles/") #Cambiar a carpeta relevante dependiendo de computadora
write.csv(BMF1_generate(50), file = "ARGS_BMFv1_Mass_Par_SmallSet.csv", row.names = FALSE)
```
```{r, Creating_infile_FAD}
set.seed(050700)
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/InputFiles/") #Cambiar a carpeta relevante dependiendo de computadora
write.csv(FAD_generate(50, 2), file = "ARGS_FADv1_Mass_Par_SmallSet.csv", row.names = FALSE)
```

```{r, Verifying_outfile}
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/")
ATFv1 <- read.table(file = "OUT_ExSSs_ATFv1_SmallSet_mY_mY.txt", header = T)
ATFv1Names <- paste0("ATFv1_", 1:nrow(ATFv1))
ATFv2 <- read.table(file = "OUT_ExSSs_ATFv2_SmallSet_mY_mY.txt", header = T)
ATFv2Names <- paste0("ATFv2_", 1:nrow(ATFv2))
#BNFv1 <- read.table(file = "OUT_ExSSs_BNFv1_SmallSet_mY_mY.txt", header = T)
#BNFv1Names <- paste0("BNFv1_", 1:nrow(BNFv1))
#BNFv2 <- read.table(file = "OUT_ExSSs_BNFv2_SmallSet_mY_mY.txt", header = T)
#BNFv2Names <- paste0("BNFv2_", 1:nrow(BNFv2))
#BMFv2 <- read.table("OUT_ExSSs_BMFv2_SmallSet_mY_mY.txt", header = T)
#BMFv2Names <- paste0("BMFv2_", 1:nrow(BMFv2))
FADv1 <- read.table(file = "OUT_ExSSs_FADv1_SmallSet_mY_mY.txt", header = T)
FADv1Names <- paste0("FADv1_", 1:nrow(FADv1))
FADv2 <- read.table(file = "OUT_ExSSs_FADv2_SmallSet_mY_mY.txt", header = T)
FADv2Names <- paste0("FADv2_", 1:nrow(FADv2))
#BMFv1 <- read.table(file = "OUT_ExSSs_BMFv1_SmallSet_mY_mY.txt", header = T)
#BMFv1Names <- paste0("BMFv1_", 1:nrow(BMFv1))
CoRas <- as.data.frame(t(rbind(ATFv1[, 2:ncol(ATFv1)], ATFv2[, 2:ncol(ATFv2)], FADv1[, 2:ncol(FADv1)], FADv2[, 2:ncol(FADv2)])))
# , BNFv1[, 2:ncol(BNFv1)], BNFv2[, 2:ncol(BNFv2)], BMFv2[, 2:ncol(BMFv2)]
rm(ATFv1, ATFv2, FADv1, FADv2)
# , BNFv1, BNFv2, BMFv2,
#, BNFv2)
#CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- c(ATFv1Names, ATFv2Names, FADv1Names, FADv2Names)
# , BNFv1Names, BNFv2Names, BMFv2Names
#BNFv2Names)
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
a <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")")))
a
```

```{r, Finding_Epsilon}
#Reference <- FreDistances(CoRas)
#write.csv(Reference, file = "Reference10.csv")
```
```{r, Using Reference}
Reference <- as.matrix(read.csv(file = "Reference10.csv", header = T))
Reference <- Reference[, 2:ncol(Reference)]
Stats <- data.frame(0, 0, 0, 0, 0)
Matrixlist <- list()
colnames(Stats) <- c("Maximum_Error", "Average_Error", "Minimum_Error", "SD_of_Error", "Epsi")
for(i in 1:3){
  epsilon <- (0.1 * (0.1)**i)
  Matrixlist[[i]] <- ErrorMat(CoRas, Reference, epsilon)
  Mistake <- ErrorMat(CoRas, Reference, epsilon)
  Stats <- rbind(Stats, ErrorCheck(Mistake, epsilon))
}

#Matrixlist

Stats <- Stats[2:nrow(Stats),]

write.csv(Stats, file = "Stats10Local.csv", row.names = F)
```

```{r, Calculating_Optimal_K}
DissimMat2 <- AUTCTest
set.seed(1337)
kcalc <- clusGap(DissimMat2, FUN = kmeans, nstart = 25, K.max = 15, B = 50)
fviz_gap_stat(kcalc)
fviz_nbclust(DissimMat2, kmeans, method = "wss")
fviz_nbclust(DissimMat2, kmeans, method = "silhouette")
```
```{r, Clustering_For_Fun}
owo <- pam(DissimMat2, diss = T, k = 5)
Cluster <-owo$clustering
DissimMat2 <- DissimMat2[names(sort(Cluster)), names(sort(Cluster))]
plot(owo)
dendrogram <- as.dendrogram(hclust(as.dist(DissimMat2), method = "average"))
  coloursdend <- c(rep("blueviolet", length(ATFv2Names)))
labels_colors(dendrogram) <- coloursdend[order.dendrogram(dendrogram)]
plot(dendrogram, cex.lab= 0.33, main = "ATFv2 1/2")
```

```{r, testing_the_function}
maybeitworks <- function(Data){
  MaxDist <- matrix(0, nrow = ncol(Data), ncol = ncol(Data))
  for(i in 1:(ncol(Data) - 1)){
    for(j in (i + 1):ncol(Data)){
      LocalMax <- 0
      iskip <- 0
      jskip <- 0
      FinishFlag <- 0
      for(k in 1:nrow(Data)){
        Buffer <- 0
        if(!(is.finite(Data[k, i]))){
          iskip <- iskip + 1
        }else{
          iskip <- 0
        }
        if(!(is.finite(Data[k, j]))){
          jskip <- jskip + 1
        }else{
          jskip <- 0
        }
        if(iskip == 0 && jskip == 0){
          Buffer <- abs(Data[k, i] - Data[k, j])
        }else if(k == nrow(Data)){
          Buffer <- sqrt((jskip * log(10 ** 0.01) - iskip * log(10 ** 0.01))**2 + (Data[k - jskip, j] - Data[k - iskip, i])**2)
          FinishFlag <- 1
        }else{
          Buffer <- sqrt(((jskip * log(10 ** 0.01) - iskip * log(10 ** 0.01))*2)**2 + (Data[k - jskip, j] - Data[k - iskip, i])**2)
        }
        if(LocalMax < Buffer){
          LocalMax <- Buffer
        }else if(FinishFlag){
          LocalMax <- LocalMax/2
        }
      }
      MaxDist[i, j] <- LocalMax
    }
  }
  MaxDist[lower.tri(MaxDist)] <- t(MaxDist)[lower.tri(MaxDist)]
  return(MaxDist)
}
```
```{r, here_we_go}
Hope2 <- maybeitworks(CoRas)
Hope2
```
```{r, ohmylord}
sum(abs(Hope - Reference) / Reference, na.rm = T) / (nrow(Reference)**2 - nrow(Reference))
```

```{r, FunctionFrechet}
FunctionFrechet <- function(Data){
  FreDist <- matrix(0, nrow = ncol(Data), ncol = ncol(Data))
  for(i in 1:(ncol(Data) - 1)){
    for(j in i:ncol(Data)){
      if(i == j){
        next
      }
      LargestMin <- 0
      for(k in 1:nrow(Data)){
        Distances <- c()
        if(is.nan(Data[k, i])){
          next
        }
        for(l in 1:nrow(Data)){
          if(!(is.nan(Data[l, j]))){
            if(l == k){
              Distances <- append(Distances, abs(Data[l, j] - Data[k, i]))
            }else if(Data[l, j] == Data[k, i]){
              Distances <- append(Distances, abs(l * log(10 ** 0.01) - k * log(10 ** 0.01)))
            }else{
              Distances <- append(Distances, sqrt((l * log(10 ** 0.01) - k * log(10 ** 0.01))**2 + (Data[l, j] - Data[k, i])**2))
            }
          }
        }
        if(LargestMin < min(Distances)){
          LargestMin <- min(Distances)
        }
      }
      FreDist[i, j] <- LargestMin
      print(paste0(i, "and", j, "evaluated"))
    }
  }
  return(FreDist)
}
```

```{r, Copium}
FunFreHope<- FunctionFrechet(CoRas[,1:3])
FunFreHope
```

```{r, AreaUnderTheCurve}
AUTC <- function(Data){
  AreaMatrix <- matrix(0, nrow = ncol(Data), ncol = ncol(Data))
  for(i in 1:(ncol(Data) - 1)){
    for(j in i:ncol(Data)){
      AccDiff <- 0
      for(k in 1:nrow(Data)){
        if(is.nan(Data[k, i]) & is.nan(Data[k, j])){
        }else if(is.nan(Data[k, i]) | is.nan(Data[k, j])){
          AccDiff <- AccDiff + 1
        }else{
          AccDiff <- AccDiff + abs(Data[k, i] - Data[k, j])
        }
      }
      AreaMatrix[i, j] <- AccDiff
    }
  }
  colnames(AreaMatrix) <- colnames(Data)
  rownames(AreaMatrix) <- colnames(Data)
  AreaMatrix[lower.tri(AreaMatrix)] <- t(AreaMatrix)[lower.tri(AreaMatrix)]
  #AreaMatrix <- AreaMatrix/max(AreaMatrix) Undocument if you want your distances normalized for some reason
  return(AreaMatrix)
}
```
```{r, Using AUTC}
AUTCTest <- AUTC(CoRas)
AUTCTest
```

```{r, ggdisplot}
ggdissplot(as.dist(DissimMat2), labels = sort(Cluster), method = NA, cluster_labels = T, cluster_lines = T, diag = F) + scale_fill_gradient(low = "darkorchid4", high = "white", na.value = "grey75")
```

```{r, Verifying_BMFv1_outfile}
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/")
BMFv1 <- read.table(file = "OUT_ExSSs_BMFv1_SmallSet_mY_mY.txt", header = T)
BMFv1Names <- paste0("BMFv1_", 1:nrow(BMFv1))
CoRas <- as.data.frame(t(BMFv1[, 2:ncol(BMFv1)]))
#rm(BMFv2)
#CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- c(BMFv1Names)
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
z <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")")))
z
```

```{r, Verifying_BMF_2_outfile}
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/")
BMFv2 <- read.table(file = "OUT_ExSSs_BMFv2_SmallSet_mY_mY.txt", header = T)
BMFv2Names <- paste0("BMFv2_", 1:nrow(BMFv2))
CoRas <- as.data.frame(t(BMFv2[, 2:ncol(BMFv2)]))
#rm(BMFv2)
CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- c(BMFv2Names)
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
z <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")")))
z
```

```{r, Verifying_FADv1_outfile}
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/")
FADv1 <- read.table(file = "OUT_ExSSs_FADv1_SmallSet_mY_mY.txt", header = T)
FADv1Names <- paste0("FADv1_", 1:nrow(FADv1))
CoRas <- as.data.frame(t(FADv1[, 2:ncol(FADv1)]))
#rm(BMFv2)
CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- c(FADv1Names)
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
z <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")"))) + ylim(c(0, 1))
z
```

```{r, Verifying_FADv2_outfile}
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/")
FADv2 <- read.table(file = "OUT_ExSSs_FADv2_SmallSet_mY_mY.txt", header = T)
FADv2Names <- paste0("FADv2_", 1:nrow(FADv2))
CoRas <- as.data.frame(t(FADv2[, 2:ncol(FADv2)]))
#rm(BMFv2)
CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- c(FADv2Names)
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
z <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")"))) + ylim(c(0,1))
z
```

```{r, altFAD_generation}
altFAD_generate <- function(rows){
  g <- abs(rnorm(rows, mean = 0.01, sd = 0.1*0.01))
  mY <- rep(0.125, rows)
  gY <- abs(rnorm(rows, mean = 0.1, sd = 0.1*0.1))
  mU <- abs(rnorm(rows, mean = 0.125, sd = 0.1*0.125))
  gU <- abs(rnorm(rows, mean = 0.05, sd = 0.1*0.5))
  mW <- abs(rnorm(rows, mean = 0.74, sd = 0.1*0.74))
  gW <- abs(rnorm(rows, mean = 0.0001, sd = 0.1*0.0001))
  e0 <- abs(rnorm(rows, mean = 0.0001, sd = 0.1*0.0001))
  eP <- abs(rnorm(rows, mean = 0.0375, sd = 0.1*0.0375))
  eM <- abs(rnorm(rows, mean = 0.5, sd = 0.1*0.5))
  mUs <- rep(NaN, rows)

  csv <- data.frame(g, mY, gY, mU, gU, mW, gW, e0, eP, eM, mUs)
  
  return(csv)
}
```
```{r, Creating_infile_altFAD}
set.seed(160396)
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/InputFiles/") #Cambiar a carpeta relevante dependiendo de computadora
write.csv(altFAD_generate(50), file = "ARGS_FADv1_Mass_Par_altSmallSet.csv", row.names = FALSE)
```
```{r, Verifying_altFADv1_outfile}
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/")
altFADv1 <- read.table(file = "OUT_ExSSs_FADv1_altSmallSet_mY_mY.txt", header = T)
altFADv1Names <- paste0("altFADv1_", 1:nrow(altFADv1))
CoRas <- as.data.frame(t(altFADv1[, 2:ncol(altFADv1)]))
#rm(BMFv2)
CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- c(altFADv1Names)
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
z <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")"))) + ylim(c(0, 1))
z
```
```{r, Verifying_altFADv2_outfile}
setwd("C:/Users/ese_1/OneDrive/Documentos/CoRa/")
altFADv2 <- read.table(file = "OUT_ExSSs_FADv2_altSmallSet_mY_mY.txt", header = T)
altFADv2Names <- paste0("altFADv2_", 1:nrow(altFADv2))
CoRas <- as.data.frame(t(altFADv2[, 2:ncol(altFADv2)]))
#rm(BMFv2)
#CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- altFADv2Names
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
z <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")"))) + ylim(c(0, 1))
#z <- ggplot(data = Graphing, aes(x = step, y = value)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")")))
z
```

```{r, seriation}
DissimMat3 <- as.dist(AUTCTest)
SerDissimMat3 <- seriate(DissimMat3, method = "ARSA")
a <- pimage(DissimMat3, main = "Unordered")
b <- pimage(DissimMat3, SerDissimMat3, main = "Seriated")
hmap(DissimMat3, method = "ARSA", row_labels = T, col = colorRampPalette(c("black", "purple"))(2500), main = "Cluster?", prop = T)
```

```{r, merging_ATFv2_by_hand}
ATFv2 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY.txt", header = T)
ATFv2_71 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_71.txt", header = T)
ATFv2_109 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_109.txt", header = T)
ATFv2_285 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_285.txt", header = T)
ATFv2_373 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_373.txt", header = T)
ATFv2_426 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_426.txt", header = T)
ATFv2_503 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_503.txt", header = T)
ATFv2_625 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_625.txt", header = T)
ATFv2_664 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_664.txt", header = T)
ATFv2_719 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_719.txt", header = T)
ATFv2_856 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_856.txt", header = T)
ATFv2_859 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_859.txt", header = T)
ATFv2_904 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_904.txt", header = T)
ATFv2_936 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_936.txt", header = T)
ATFv2_947 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_947.txt", header = T)
ATFv2_979 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_979.txt", header = T)
ATFv2_982 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_982.txt", header = T)
ATFv2_1004 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_1004.txt", header = T)
ATFv2_1182 <- read.table(file = "OUT_ExSSs_ATFv2_1250Set1_mY_mY_From_1182.txt", header = T)
ATFv2_Merged <- rbind(ATFv2, ATFv2_71, ATFv2_109, ATFv2_285, ATFv2_373, ATFv2_426, ATFv2_503, ATFv2_625, ATFv2_664, ATFv2_719, ATFv2_856, ATFv2_859, ATFv2_904, ATFv2_936, ATFv2_947, ATFv2_979, ATFv2_982, ATFv2_1004, ATFv2_1182)
BNFv2 <- read.table(file = "OUT_ExSSs_BNFv2_1250Set1_mY_mY.txt", header = T)
rm(ATFv2, ATFv2_71, ATFv2_109, ATFv2_285, ATFv2_373, ATFv2_426, ATFv2_503, ATFv2_625, ATFv2_664, ATFv2_719, ATFv2_856, ATFv2_859, ATFv2_904, ATFv2_936, ATFv2_947, ATFv2_979, ATFv2_982, ATFv2_1004, ATFv2_1182)
ATFv2_Names <- paste0("ATFv2_", 1:nrow(ATFv2_Merged))
BNFv2_Names <- paste0("BNFv2_", 1:nrow(BNFv2))
CoRas <- as.data.frame(t(rbind(ATFv2_Merged[, 2:ncol(ATFv2_Merged)], BNFv2[, 2:ncol(BNFv2)])))
CoRas[CoRas > 1] <- NaN
colnames(CoRas) <- c(ATFv2_Names, BNFv2_Names)
Graphing <- tidyr::gather(CoRas)
Graphing$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas))
a <- ggplot(data = Graphing, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")")))
a
```

```{r, graphing_Cluster_Members}
Partial = tidyr::gather(CoRas[, names(Cluster[which(Cluster == 5)])])
Partial$step <- rep(seq(from = 0, to = 0.01, by = 1/60000), ncol(CoRas[, names(Cluster[which(Cluster == 5)])]))
b <- ggplot(data = Partial, aes(x = step, y = value, col = key)) + geom_line(size = 1.5) + theme(legend.position = "none") + ylab(expression(paste("CoRa"[mu[Y]%in%theta], "("*mu[Y],")")))
b
```